config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads do
      resource :like, module: :forum_posts
    end
  end

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
	belongs_to :forum_thread
	belongs_to :user

	validates :body, presence: true

	def send_notifications!
		users = forum_thread.users.uniq - [user]

		users.each do |user|
			Notificationmailer.forum_post_notification(user, self).deliver_later
		end
	end
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
	belongs_to :user
	has_many :forum_posts
	has_many :users, through: :forum_posts

	accepts_nested_attributes_for :forum_posts

	validates :subject, presence: true
	validates_associated :forum_posts
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :forum_threads
         has_many :forum_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new forum_post_params
    @forum_post.user = current_user

    if @forum_post.save
      @forum_post.send_notifications!
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}"), notice: "Successfully posted!"
    else
      redirect_to @forum_thread, alert: "Unable to save your post"
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads/likes_controller.rb
class ForumPosts::LikesController < ApplicationController
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_forum_thread, except: [:index, :new, :create]

	def index
		@q = ForumThread.search(params[:q])
		@forum_threads = @q.result(distinct: true)
	end	

	def show
		@forum_post = ForumPost.new
	end	

	def new
		@forum_thread = ForumThread.new
		@forum_thread.forum_posts.new
	end

	def create
		@forum_thread = current_user.forum_threads.new forum_thread_params
		@forum_thread.forum_posts.first.user_id = current_user.id

		if @forum_thread.save
			redirect_to @forum_thread
		else
			render action: :new
		end
	end

	private

		def set_forum_thread
			@forum_thread = ForumThread.find(params[:id])
		end

		def forum_thread_params
			params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/forum_posts/_forum_post.html.erb
<%= div_for forum_post do %>
  <p class="text-muted">Posted by <%= forum_post.user.email %> <%= local_time_ago forum_post.created_at %></p>
  <p><%= forum_post.body %></p>
<% end %>

<div id="likes">
	<%= render partial: "likes" %>
</div>

app/views/forum_posts/_likes.html.erb
<%= link_to "Like", forum_thread_forum_post_like(@forum_post), method: :post %>

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
	<div class="form-group">
		<%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
	</div>

	<%= f.fields_for :forum_posts do |p| %>
		<div class="form-group">
			<%= p.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.submit %>
	</div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
  <h3><%= forum_thread.subject %></h3>
<% end %>

app/views/forum_threads/index.html.erb
<div class="container">
  <div class="pull-right">
    <%= link_to "New Thread", new_forum_thread_path, class: "btn btn-success" %>
  </div>
  <div class="pull-right" style="margin-right: 10px">
	<%= search_form_for @q, html: {class: "form-inline"} do |f| %>
		<%= f.search_field :subject_or_forum_posts_body_cont, placeholder: "Search...", class: "form-control" %>
		<%end%>
  </div>

  <h1 class="page-header">Forum Threads</h1>
  <%= render @forum_threads %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>
  <p class="text-muted">Created by <%= @forum_thread.user.email %></p>
  <%= render @forum_thread.forum_posts %>

  <hr />
  <%= render partial: "forum_posts/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= link_to "Threads", forum_threads_path %>
<%= yield %>

</body>
</html>